name = "Gay Minecraft"
author = "reallyriley"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa8fe5e4aa4353aa48f7d85375eb5503c791016d14b1dd16ac7846b8dc1d92b6"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
