name = "Gay Minecraft"
author = "reallyriley"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5a2635621a68b3cf288b2a607c51a02b0b6a260966094dcdb81c3f11665bc48"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
